name: "Lint Tests"

on:
  push:
  workflow_call:
  pull_request:

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@2.0.1
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write
