name: "Lint Tests"

on:
  push

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.0.3
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write
