name: "nightly"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  lint-unit:
    name: "Run Chef lint tests"
    uses: ./.github/workflows/lint.yml

  integration:
    name: "Run Chef integration tests"
    uses: ./.github/workflows/ci.yml
    secrets:
      FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
      FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
      FALCON_CID: ${{ secrets.FALCON_CID }}
      FALCON_CLOUD: ${{ secrets.FALCON_CLOUD }}
      FALCON_VERSION: ${{ secrets.FALCON_VERSION }}
